

# x,y, w,h 代表 坐标和宽高
# 注意：每一项操作都在前一项操作的结果上进行


# 视频路径
videoPath = "./video"
system = 0

appId = "85b026d19f6940aa6a58a966346e1abf"

## 独立模块
# 视频分段
# duration 每一段的时长（单位：秒）
[cutSection]
    sectionPath = "./section"
    switch = false
    duration = 10

# 视频截图
#  t 表示共要多少时间
#  r 表示每一秒几帧
[Snip]
    switch = false
    t = 1
    r = 1

## 1. 视频格式转换
[format]
    switch = false
    form = "mp4"

## 2. 帧率设置
## eg: +5 在原来的基础上+5  -5 在原来的基础上-5   20 修改为20
[frameRate]
    switch = false
    value = "+5"

## 3. 码率设置
## eg: +5 在原来的基础上+5  -5 在原来的基础上-5   20 修改为20
[bitRate]
    switch = false
    value = "+5"

## 4. 减掉视频前几秒
[cutFront]
    switch = false
    value = 6

## 5. 减掉视频最后几秒
[cutBack]
    switch = false
    value = 4

# 6. 视频剪裁
# 如果全部剪裁 start duration 填0
# start = 5 duration = 10 含义 从第5秒开始，剪裁往后的10秒
[crop]
    switch = false
    start = 0  #从第几秒开始剪裁 （可选）
    duration = 0 # 剪裁时长（可选）
    x = 320
    y = 1
    w = 300
    h = 534


## 7. 去除水印
[clearWater]
    switch = false
    x = 10
    y = 10
    w = 100
    h = 50

# 镜像
# direction  h : 水平方向（左右镜像） v：垂直方向（上下镜像）
[mirror]
    switch = false
    direction = "v"

## 8. 调整视频分辨率
[resolution]
    switch = false
    w = 576
    h = 1024

##压缩,一般 调整 crf 即可
[compress]
    switch = true
    preset = "medium" #（ultrafast，superfast，veryfast，faster，fast，medium，slow，slower，veryslow和placebo）
    crf = 40 # 指定输出视频的质量，取值范围是0-51，默认值为23，数字越小输出视频的质量越高

## 9. 文字水印
[waterText]
    switch = false
    content = "文字logo"
    path = "./source/simsun.ttc"
    size = 50
    color = "red"
    alpha = 0.8
    style = 1
    sp1 = 50
    sp2 = 100

## 9.1 滚动文字
# isTop 顶部还是底部 sp 距离顶部或者底部的距离
# leftToRight 是否从坐到右
[runWaterText]
    switch = false
    content = "测试文字"
    path = "./source/simsun.ttc"
    size = 50
    color = "red"
    isTop = true
    leftToRight = true
    sp = 50


## 10. 图片水印
[waterImage]
    switch = false
    path = "./source/item.png"
    style = 3
    sp1 = 50
    sp2 = 100

# 11. 倍速播放（取值范围 0.5~2）0.5 速度减慢一倍，2 速度加快一倍，1 速度不变
[speed]
    switch = false
    v = "2"

## 12. 片头
[filmTitle]
    switch = false
    path = "./source/head.mp4"

## 13. 片尾
[filmEnd]
    switch = false
    path = "./source/foot.mp4"

