

# x,y, w,h 代表 坐标和宽高
# 注意：每一项操作都在前一项操作的结果上进行


# 视频路径
videoPath = "./video"
system = 0
## 1. 视频格式转换
[format]
    switch = true
    form = "mp4"

## 2. 帧率设置
## eg: +5 在原来的基础上+5  -5 在原来的基础上-5   20 修改为20
[frameRate]
    switch = true
    value = "+5"

## 3. 码率设置
## eg: +5 在原来的基础上+5  -5 在原来的基础上-5   20 修改为20
[bitRate]
    switch = true
    value = "+5"

## 4. 减掉视频前几秒
[cutFront]
    switch = true
    value = 2

## 5. 减掉视频最后几秒
[cutBack]
    switch = true
    value = 2

# 6. 视频剪裁
# 如果全部剪裁 start duration 填0
# start = 5 duration = 10 含义 从第5秒开始，剪裁往后的10秒
[crop]
    switch = false
    start = 5  #从第几秒开始剪裁 （可选）
    duration = 10 # 剪裁时长（可选）
    x = 10
    y = 10
    w = 100
    h = 50

## 7. 去除水印
[clearWater]
    switch = true
    x = 10
    y = 10
    w = 100
    h = 50


## 8. 调整视频分辨率
[resolution]
    switch = false
    w = 1084
    h = 1920

## 9. 文字水印
## eg: +5 在原来的基础上+5  -5 在原来的基础上-5   20 修改为20
[waterText]
    switch = true
    content = "测试文字"
    path = "./source/simsun.ttc"
    size = 50
    color = "black"
    alpha = 0.8
    style = 1
    sp1 = 50
    sp2 = 100


## 10. 图片水印
[waterImage]
    switch = true
    path = "./source/item.jpg"
    style = 2
    sp1 = 50
    sp2 = 100

# 11. 倍速播放（取值范围 0.5~2）0.5 速度减慢一倍，2 速度加快一倍，1 速度不变
[speed]
    switch = true
    v = "2"

## 12. 片头
[filmTitle]
    switch = true
    path = "./source/film.mp4"

## 13. 片尾
[filmEnd]
    switch = true
    path = "./source/film.mp4"

