
#* [x] [1. 视频格式转换]
#* [x] [2. 帧率设置]
#* [x] [3. 比特率设置]
#* [x] [4. 减掉视频前几秒]
#* [x] [5. 减掉视频最后几秒]
#* [x] [6. 去除水印]
#* [x] [7. 调整视频分辨率]
#* [x] [8. 添加文字水印]
#* [x] [9. 添加图片水印]
#* [x] [10. 添加片头]
#* [x] [11. 添加片尾]

# 视频路径
videoPath = "./video"
system = 0
## 1. 视频格式转换
[format]
    switch = true
    form = "mp4"

## 2. 帧率设置
## eg: +5 在原来的基础上+5  -5 在原来的基础上-5   20 修改为20
[frameRate]
    switch = true
    value = "+5"

## 3. 码率设置
## eg: +5 在原来的基础上+5  -5 在原来的基础上-5   20 修改为20
[bitRate]
    switch = true
    value = "+5"

## 4. 减掉视频前几秒
[cutFront]
    switch = true
    value = 2

## 5. 减掉视频最后几秒
[cutBack]
    switch = true
    value = 2

## 6. 去除水印
[clearWater]
    switch = true
    x = 10
    y = 10
    w = 100
    h = 50

## 7. 调整视频分辨率
[resolution]
    switch = false
    w = 1084
    h = 1920
## 8. 文字水印
## eg: +5 在原来的基础上+5  -5 在原来的基础上-5   20 修改为20
[waterText]
    switch = true
    content = "测试文字"
    path = "./source/simsun.ttc"
    size = 50
    color = "black"
    alpha = 0.8
    style = 1
    sp1 = 50
    sp2 = 100


## 9. 图片水印
[waterImage]
    switch = true
    path = "./source/item.jpg"
    style = 2
    sp1 = 50
    sp2 = 100

## 10. 片头
[filmTitle]
    switch = true
    path = "./source/film.mp4"

## 11. 片尾
[filmEnd]
    switch = true
    path = "./source/film.mp4"

