# **********************************************************************#
#                                                                       #
#       密钥购买地址：https://www.kuaifaka.com/purchasing?link=3ZUpQ      #
#                                                                       #
# **********************************************************************#

# **********************************************************************#
#                         注意事项
#  1. windows 系统，此文件不能用记事本打开修改
#  2. 支持的视频格式 "mp4","avi","flv","webm","mpeg","divx","mov","asf","wmf","rm","rmvb","ts"
#  3. 支持的音频格式 "mp3","wav","midi","wma","ogg","ape"
#  4. x,y, w,h 代表 坐标和宽高
#  5. 每一项操作都在前一项操作的结果上进行，可同时打开多项功能
#  6. 功能开关： 1 打开   0 关闭
#
# **********************************************************************#



# 视频路径
videoPath = "./video"

# 如果程序无法识别系统 手动填写 MacOS  =1 Linux = 2 Win32 = 3 Win64 = 4
system = 0

# 空闲时间每隔几分钟检测 video 是否有视频，若有则处理,处理完成后将文件移到 output
# 此项功能是配合自动发布器使用
task = 0
output = ""


# 密钥
appId = "86b026d19f6940aa6a58a966346e1abf"

############################# 独立模块 ################################
# 视频分段
# duration 每一段的时长（单位：秒）
[cutSection]
    switch = 0
    sectionPath = "./section"
    duration = 10

# 随机合并
# 随机选择几个合并
[mergeSection]
    switch = 1
    MergePath = "./merge"
    count = 6

# 视频截图
#  t 表示共要多少时间
#  r 表示每一秒几帧
[Snip]
    switch = 0
    t = 1
    r = 1
############################# 独立模块 ################################




###################### 下面为视频剪辑相关操作 ##########################

## 1. 视频格式转换
## form 输出格式
[format]
    switch = 0
    form = "mp4"

## 2. 帧率设置
## eg: +5 在原来的基础上+5  -5 在原来的基础上-5   20 修改为20
[frameRate]
    switch = 0
    value = "+5"

## 3. 码率设置
## eg: +5 在原来的基础上+5  -5 在原来的基础上-5   20 修改为20
[bitRate]
    switch = 0
    value = "+5"

## 4. 减掉视频前几秒
[cutFront]
    switch = 0
    value = 7

## 5. 减掉视频最后几秒
[cutBack]
    switch = 0
    value = 7

# 两种剪裁方式，只能选择一种
# 6. 视频剪裁
# 如果全部剪裁 start duration 填0
# start = 5 duration = 10 含义 从第5秒开始，剪裁往后的10秒
# 通过坐标及区域剪裁
[crop]
    switch = 0
    start = 0  #从第几秒开始剪裁 （可选）
    duration = 0 # 剪裁时长（可选）
    x = 320
    y = 1
    w = 300
    h = 534

# 6.1 视频剪裁
# 如果全部剪裁 start duration 填0
# start = 5 duration = 10 含义 从第5秒开始，剪裁往后的10秒
# left 左边减去多少个像素
# right 右边减去多少个像素
# top 顶部减去多少个像素
# bottom 底部减去多少个像素
[crop1]
    switch = 0
    start = 0  #从第几秒开始剪裁 （可选）
    duration = 0 # 剪裁时长（可选）
    left = 10
    right = 20
    top = 40
    bottom = 40

## 7. 去除水印 ，可以设置两个位置
[clearWater]
    switch = 0
    x = 10
    y = 10
    w = 100
    h = 50

[clearWater1]
    switch = 0
    x = 10
    y = 10
    w = 100
    h = 50

# 8.镜像
# direction  h : 水平方向（左右镜像） v：垂直方向（上下镜像）
[mirror]
    switch = 0
    direction = "v"

## 9. 调整视频分辨率
[resolution]
    switch = 0
    w = 576
    h = 1024

## 10. 压缩,一般 调整 crf 即可
[compress]
    switch = 0
    preset = "medium" #（ultrafast，superfast，veryfast，faster，fast，medium，slow，slower，veryslow和placebo）
    crf = 40 # 指定输出视频的质量，取值范围是0-51，默认值为23，数字越小输出视频的质量越高

## 11. 文字水印
# content 文字内容
# path 字体路径，对字体没有要求不要更改
# size 字体大小
# color 字体颜色，eg: red black white blue yellow ...
# alapha 字体透明度（0~1.0）
# style 字体位置（1~9）
# sp1 水平方向距离边界的距离
# sp2 竖直方向距离边界的距离
[waterText]
    switch = 0
    content = "微信 cywt123"
    path = "./source/simsun.ttc"
    size = 30
    color = "red"
    alpha = 1.0
    style = 1
    sp1 = 20
    sp2 = 30

## 11.1 滚动文字
# isTop 顶部还是底部 sp 距离顶部或者底部的距离
# leftToRight 是否从左到右移动 1 从左到右 0 从右到左
# 其他参数同上
[runWaterText]
    switch = 0
    content = "微信 cywt123"
    path = "./source/simsun.ttc"
    size = 30
    color = "black"
    isTop = 1
    leftToRight = 1
    sp = 50


## 12. 图片水印
# content 文字内容
# path 图片路径，将图片放入source 文件夹，然后修改path
# style 字体位置（1~9）
# sp1 水平方向距离边界的距离
# sp2 竖直方向距离边界的距离
[waterImage]
    switch = 0
    path = "./source/item.png"
    style = 3
    sp1 = 50
    sp2 = 100

## 13. 添加背景音乐
# 将背景音乐放入bgm 文件夹，可以放多个背景音乐，随机给视频添加背景音乐，如果音乐比视频短，则音乐会循环播放
# cover 是否覆盖 0:保留原有音频，同时添加新的背景音乐  1: 去除原有音频，添加新背景音乐
[addBgm]
    switch = 0
    cover = 1
    bgm = "./bgm"


## 14. 倍速播放（取值范围 0.5~2）0.5 速度减慢一倍，2 速度加快一倍，1 速度不变
[speed]
    switch = 0
    v = "2"

## 15. 片头
# path 片头路径
[filmTitle]
    switch = 0
    path = "./source/head.mp4"

## 16. 片尾
# path 片尾路径
[filmEnd]
    switch = 0
    path = "./source/foot.mp4"

